x-variables:
  main-image: &main-image localhost/local-dev/cork-service-status-base:local-dev
services:
  app:
    image: *main-image
    env_file:
      - .env
    ports:
      - ${APP_HOST_PORT:-3000}:${APP_CONTAINER_PORT:-3000}
    volumes:
      - ../../../services/package.json:/services/package.json
      - ../../../services/package-lock.json:/services/package-lock.json
      - ../../../services/lib:/services/lib
      - ../../../services/data-seeder:/services/data-seeder

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: localhost
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../../services/pg/schema:/docker-entrypoint-initdb.d
  postgrest:
    image: postgrest/postgrest
    ports:
      - ${POSTGREST_HOST_PORT:-3001}:${POSTGREST_CONTAINER_PORT:-3000}
    environment:
      PGRST_DB_URI: postgres://postgres:localhost@db:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:${POSTGREST_HOST_PORT:-3001}
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - ${SWAGGER_HOST_PORT:-3002}:${SWAGGER_CONTAINER_PORT:-8080}
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3001/
    depends_on:
      - postgrest
  adminer:
    image: adminer:5
    ports:
      - ${ADMINER_HOST_PORT:-8080}:8080
volumes:
  db-data:
